version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: '-'
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: '-'
