version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: '-'
    groups:
      minor-updates:
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: '-'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: '-'
